https://energiaeambiente.org.br/qual-a-diferenca-entre-gases-de-efeito-estufa-e-poluentes-atmosfericos-20220511#:~:text=Os%20principais%20GEE%20emitidos%20por,de%20combust%C3%ADveis%20ou%20pelo%20desmatamento.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
import statsmodels.stats.api as sms
from statsmodels.formula.api import ols
pd.set_option('display.max_columns', None)

In [2]:
df_emissions = pd.read_csv('../data/Gas Emissions/total-ghg-emissions.csv',comment='#', low_memory=False)
#df_emissions.drop(df_emissions[
#    (df_emissions['Entity'] != 'South America') &
#    (df_emissions['Entity'] != 'North America') &
#    (df_emissions['Entity'] != 'Europe') &
#    (df_emissions['Entity'] != 'Africa') &
#    (df_emissions['Entity'] != 'Oceania') &
#    (df_emissions['Entity'] != 'Asia')
#].index, inplace=True)
#df_emissions.drop('Code', axis=1, inplace=True)
df_emissions.columns = ['COUNTRY', 'CODE', 'DATE', 'EMISSIONS']

In [3]:
df_emissions

COUNTRY CODE  DATE     EMISSIONS
0     Afghanistan  AFG  1990  9.580000e+06
1     Afghanistan  AFG  1991  9.810000e+06
2     Afghanistan  AFG  1992  9.030000e+06
3     Afghanistan  AFG  1993  9.110000e+06
4     Afghanistan  AFG  1994  9.150000e+06
...           ...  ...   ...           ...
6144     Zimbabwe  ZWE  2015  4.230000e+07
6145     Zimbabwe  ZWE  2016  1.159200e+08
6146     Zimbabwe  ZWE  2017  1.155900e+08
6147     Zimbabwe  ZWE  2018  1.182200e+08
6148     Zimbabwe  ZWE  2019  1.179600e+08

[6149 rows x 4 columns]

In [4]:
df_emissions.COUNTRY.unique()

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Asia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
       'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba',
       'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Europe', 'European Union (27)', 'Fiji',
       'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Gr

In [5]:
df_emissions.head(3)

COUNTRY CODE  DATE     EMISSIONS
0  Afghanistan  AFG  1990  9.580000e+06
1  Afghanistan  AFG  1991  9.810000e+06
2  Afghanistan  AFG  1992  9.030000e+06

In [6]:
df_iqar = pd.read_csv('../data/air-quality/results/iqar-countries-class-after.csv',comment='#', low_memory=False)

In [7]:
df_iqar

DATE CODE       MEAN  CLASSIFICATION
0    2014  AUS  18.392635        0.166667
1    2014  AUT  25.457333        0.400000
2    2014  BEL  21.207407        0.333333
3    2014  BOL   9.266667        0.000000
4    2014  BRA  15.391667        0.166667
..    ...  ...        ...             ...
664  2022  UKR  18.184177        0.500000
665  2022  USA  13.672793        0.166667
666  2022  UZB  88.309392        2.000000
667  2022  VNM  19.482719        0.166667
668  2022  ZAF  18.248637        0.166667

[669 rows x 4 columns]

In [8]:
df = pd.merge(df_iqar, df_emissions,  how='inner', on=['CODE','DATE'])
df.head(10)

DATE CODE       MEAN  CLASSIFICATION      COUNTRY     EMISSIONS
0  2014  AUS  18.392635        0.166667    Australia  5.699800e+08
1  2014  AUT  25.457333        0.400000      Austria  6.808000e+07
2  2014  BEL  21.207407        0.333333      Belgium  1.041500e+08
3  2014  BOL   9.266667        0.000000      Bolivia  1.167200e+08
4  2014  BRA  15.391667        0.166667       Brazil  1.384990e+09
5  2014  CAN   8.293134        0.000000       Canada  8.421400e+08
6  2014  CHE  16.400000        0.000000  Switzerland  4.691000e+07
7  2014  CHL  16.054090        0.166667        Chile  1.525000e+07
8  2014  CHN  52.435908        1.166667        China  1.122848e+10
9  2014  COL  14.338889        0.166667     Colombia  2.311500e+08

## Coverage

In [9]:
df_iqar.DATE.unique()

array([2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022], dtype=int64)

In [10]:
df_emissions.DATE.unique()

array([1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,
       2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019], dtype=int64)

In [11]:
df.DATE.unique()

array([2014, 2015, 2016, 2017, 2018, 2019], dtype=int64)

In [12]:
df.tail(10)

DATE CODE        MEAN  CLASSIFICATION        COUNTRY     EMISSIONS
357  2019  THA   21.660153        0.333333       Thailand  4.371800e+08
358  2019  TJK  127.767677        3.000000     Tajikistan  1.738000e+07
359  2019  TKM   63.218935        2.000000   Turkmenistan  1.573300e+08
360  2019  TUR   26.588440        0.666667         Turkey  4.598600e+08
361  2019  UGA  133.613699        3.000000         Uganda  5.915000e+07
362  2019  UKR   31.753694        0.500000        Ukraine  2.212900e+08
363  2019  USA   14.517852        0.166667  United States  5.771000e+09
364  2019  UZB   99.659306        2.000000     Uzbekistan  1.853900e+08
365  2019  VNM   28.892669        0.500000        Vietnam  4.381100e+08
366  2019  ZAF   18.843618        0.166667   South Africa  5.621900e+08

In [13]:
df.CLASSIFICATION.unique()

array([0.16666667, 0.4       , 0.33333333, 0.        , 1.16666667,
       0.83333333, 1.33333333, 1.        , 0.2       , 2.        ,
       0.8       , 0.66666667, 0.25      , 0.5       , 3.        ,
       1.5       , 0.6       ])

## Modelando com base nas emissões

In [14]:
from sklearn.preprocessing import MinMaxScaler

df_sklearn = df.copy()
  
df_sklearn['CLASSIFICATION'] = MinMaxScaler().fit_transform(np.array(df_sklearn['CLASSIFICATION']).reshape(-1,1))
df_sklearn['EMISSIONS'] = MinMaxScaler().fit_transform(np.array(df_sklearn['EMISSIONS']).reshape(-1,1))
  
display(df_sklearn)

DATE CODE       MEAN  CLASSIFICATION        COUNTRY  EMISSIONS
0    2014  AUS  18.392635        0.055556      Australia   0.061623
1    2014  AUT  25.457333        0.133333        Austria   0.020617
2    2014  BEL  21.207407        0.111111        Belgium   0.023564
3    2014  BOL   9.266667        0.000000        Bolivia   0.024591
4    2014  BRA  15.391667        0.055556         Brazil   0.128211
..    ...  ...        ...             ...            ...        ...
362  2019  UKR  31.753694        0.166667        Ukraine   0.033135
363  2019  USA  14.517852        0.055556  United States   0.486554
364  2019  UZB  99.659306        0.666667     Uzbekistan   0.030202
365  2019  VNM  28.892669        0.166667        Vietnam   0.050849
366  2019  ZAF  18.843618        0.055556   South Africa   0.060987

[367 rows x 6 columns]

In [15]:
import statsmodels.formula.api as smf
model = smf.ols("CLASSIFICATION ~ EMISSIONS", data=df_sklearn)
response = model.fit()
response.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:         CLASSIFICATION   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.003
Method:                 Least Squares   F-statistic:                   0.01873
Date:                Fri, 02 Dec 2022   Prob (F-statistic):              0.891
Time:                        23:22:30   Log-Likelihood:                 8.3094
No. Observations:                 367   AIC:                            -12.62
Df Residuals:                     365   BIC:                            -4.808
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.1815      0.014     13.189      0.000       0.154       0.209
EMISSIONS     -0.0126      0.092     -0.137      0.891      -0.194       0.168
==============================================================================
Omnibus:                      169.291   Durbin-Watson:                   2.119
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              555.878
Skew:                           2.194   Prob(JB):                    1.96e-121
Kurtosis:                       7.136   Cond. No.                         7.46
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""